import "server-only";
import { type ManufacturerSource, isUrlOnManufacturerSource } from "./manufacturerSourceRegistry";

export type ManufacturerCatalogProduct = { brand:string; title:string; url:string; price:number; imageUrl?:string };
const FETCH_TIMEOUT_MS=4000;
const MAX_PRODUCTS_PER_SOURCE=80;
const CACHE_SECONDS=21600;

function decodeHtml(v:string){return v.replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&apos;/gi,"'").replace(/&nbsp;/gi," ").replace(/&reg;/gi,"®").replace(/&trade;/gi,"™").replace(/&#x2F;/gi,"/").replace(/&#47;/gi,"/").replace(/&#(\d+);/g,(_,c:string)=>{const n=Number(c);return Number.isFinite(n)?String.fromCharCode(n):""})}
function stripHtml(v:string){return decodeHtml(v.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim()}
function numberValue(v:unknown){if(typeof v==="number"&&Number.isFinite(v))return v;if(typeof v!=="string")return null;const n=Number(v.replace(/[^0-9.]/g,""));return Number.isFinite(n)?n:null}
function stringValue(v:unknown){return typeof v==="string"?v.trim():""}
function firstString(v:unknown):string{if(typeof v==="string")return v.trim();if(Array.isArray(v)){for(const x of v){const s=firstString(x);if(s)return s}}if(v&&typeof v==="object"){const r=v as Record<string,unknown>;return firstString(r.url)||firstString(r.contentUrl)}return ""}
function offerPrice(v:unknown):number|null{if(!v||typeof v!=="object")return null;if(Array.isArray(v)){for(const x of v){const p=offerPrice(x);if(p!==null)return p}return null}const r=v as Record<string,unknown>;return numberValue(r.price)??numberValue(r.lowPrice)??numberValue(r.highPrice)}
function isProductType(v:unknown){if(typeof v==="string")return v.toLowerCase()==="product";if(Array.isArray(v))return v.some(isProductType);return false}
function collectJsonLd(v:unknown,source:ManufacturerSource,out:ManufacturerCatalogProduct[]){if(Array.isArray(v)){for(const x of v)collectJsonLd(x,source,out);return}if(!v||typeof v!=="object")return;const r=v as Record<string,unknown>;if(isProductType(r["@type"])){const title=stringValue(r.name),url=firstString(r.url),price=offerPrice(r.offers),imageUrl=firstString(r.image);if(title&&url&&price!==null&&price>0&&isUrlOnManufacturerSource(url,source))out.push({brand:source.canonicalBrand,title,url,price,imageUrl:imageUrl||undefined})}for(const x of Object.values(r)){if(x&&typeof x==="object")collectJsonLd(x,source,out)}}
function parseJsonLd(html:string,source:ManufacturerSource){const out:ManufacturerCatalogProduct[]=[];const rx=/<script\b[^>]*type\s*=\s*["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m:RegExpExecArray|null;while((m=rx.exec(html))!==null){try{collectJsonLd(JSON.parse(decodeHtml(m[1].trim())),source,out)}catch{}}return out}
function attr(tag:string,name:string){return decodeHtml(tag.match(new RegExp(`${name}\\s*=\\s*["']([^"']+)["']`,"i"))?.[1]??"")}
function slugTitle(v:string){try{const u=new URL(v);const slug=(u.pathname.split("/").filter(Boolean).at(-1)??"").replace(/\.(?:html?|aspx?)$/i,"");return slug.split(/[-_]+/).filter(Boolean).map(p=>p.charAt(0).toUpperCase()+p.slice(1)).join(" ")}catch{return ""}}
function parseAnchors(html:string,source:ManufacturerSource){const out:ManufacturerCatalogProduct[]=[];const rx=/(<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>)([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;while((m=rx.exec(html))!==null){let url:string;try{url=new URL(decodeHtml(m[2]),source.origin).toString()}catch{continue}if(!isUrlOnManufacturerSource(url,source))continue;const block=m[3],text=stripHtml(block),pm=text.match(/\$\s*([0-9]{1,4}(?:\.[0-9]{1,2})?)/);if(!pm)continue;const price=Number(pm[1]);if(!Number.isFinite(price)||price<=0)continue;const hm=block.match(/<(?:h2|h3|h4)\b[^>]*>([\s\S]*?)<\/(?:h2|h3|h4)>/i);const aria=attr(m[1],"aria-label").replace(/^(?:shop|buy|view|learn more about)\s+/i,"").trim();const title=(hm?stripHtml(hm[1]):"")||aria||slugTitle(url);if(!title||title.length<2||title.length>180)continue;const imgTag=block.match(/<img\b[^>]*>/i)?.[0]??"";const rawImg=attr(imgTag,"src")||attr(imgTag,"data-src");let imageUrl:string|undefined;if(rawImg){try{imageUrl=new URL(rawImg,source.origin).toString()}catch{}}out.push({brand:source.canonicalBrand,title,url,price,imageUrl})}return out}
async function fetchCatalogPage(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),FETCH_TIMEOUT_MS);try{const r=await fetch(url,{method:"GET",headers:{Accept:"text/html,application/xhtml+xml"},next:{revalidate:CACHE_SECONDS},signal:c.signal});if(!r.ok)throw new Error(`Manufacturer catalog request returned ${r.status}.`);return await r.text()}finally{clearTimeout(t)}}
export async function discoverManufacturerProducts(source:ManufacturerSource){const pages=await Promise.allSettled(source.catalogUrls.map(fetchCatalogPage));const products:ManufacturerCatalogProduct[]=[];for(const page of pages){if(page.status!=="fulfilled")continue;products.push(...parseJsonLd(page.value,source),...parseAnchors(page.value,source))}const unique=new Map<string,ManufacturerCatalogProduct>();for(const p of products){const key=p.url.split("#")[0].replace(/\/$/,"");if(!unique.has(key))unique.set(key,p)}return Array.from(unique.values()).slice(0,MAX_PRODUCTS_PER_SOURCE)}
