export type ProductScoringInput = {

    /*
     * Overall product quality.
     * (Bioavailability, formulation,
     * ingredient forms, etc.)
     */
    quality: number;
   
    /*
     * Customer review score.
     */
    reviews: number;
   
    /*
     * Value score generated by the
     * pricing engine.
     */
    value: number;
   
    /*
     * Scientific evidence and
     * manufacturer transparency.
     */
    evidence: number;
   
    /*
     * Availability across trusted
     * vendors.
     */
    availability: number;
   
    /*
     * Ingredient cleanliness.
     */
    cleanIngredients: number;
   
    /*
     * Third-party testing.
     */
    certifications: number;
   
    /*
     * Confidence in the AI research.
     */
    aiConfidence: number;
   
    /*
     * Completeness of gathered data.
     */
    dataCompleteness: number;
   
   };