import type { CatalogProduct } from "./types";

export const VIDAPOUCH_CATALOG: CatalogProduct[] = [
 {
   id: "multivitamin",
   name: "multivitamin",
   displayName: "Daily Multivitamin",
   description:
     "Foundational daily wellness support with essential vitamins and minerals.",
   category: "general_wellness",
   defaultTiming: "morning",
   monthlyPrice: 28,
   dosage: "2 capsules",
   brand: "VidaPouch",
   supports: ["general_wellness", "immune_support", "energy"],
   pairsWellWith: ["omega3", "fish-oil", "probiotic", "vitamin-d3", "magnesium"],
   suggestionPriority: 8,
   corePriority: 9,
 },
 {
   id: "omega3",
   name: "omega3",
   displayName: "Omega-3",
   description:
     "Daily omega-3 support for heart, brain, and overall wellness.",
   category: "heart_brain",
   defaultTiming: "morning",
   monthlyPrice: 24,
   dosage: "2 softgels",
   brand: "VidaPouch",
   supports: [
     "heart_circulation",
     "focus_brain",
     "general_wellness",
     "healthy_aging",
     "eye_health",
     "bone_joint",
   ],
   pairsWellWith: ["coq10", "vitamin-d3", "multivitamin", "lutein", "vitamin-e"],
   suggestionPriority: 9,
   corePriority: 9,
 },
 {
   id: "fish-oil",
   name: "fish-oil",
   displayName: "Fish Oil",
   description:
     "Supports heart, brain, and joint wellness with essential omega-3 fatty acids.",
   category: "heart_brain",
   defaultTiming: "morning",
   monthlyPrice: 25,
   dosage: "2 softgels",
   brand: "VidaPouch",
   supports: [
     "heart_circulation",
     "focus_brain",
     "bone_joint",
     "healthy_aging",
     "eye_health",
     "general_wellness",
   ],
   pairsWellWith: ["coq10", "vitamin-d3", "multivitamin", "lutein", "vitamin-e"],
   suggestionPriority: 8,
   corePriority: 8,
 },
 {
   id: "vitamin-d3",
   name: "vitamin-d3",
   displayName: "Vitamin D3",
   description:
     "Supports immune function, mood balance, and bone health.",
   category: "immune_bone_mood",
   defaultTiming: "morning",
   monthlyPrice: 17,
   dosage: "1 softgel",
   brand: "VidaPouch",
   supports: ["immune_support", "bone_joint", "stress_mood", "general_wellness"],
   pairsWellWith: ["vitamin-k2", "calcium", "omega3", "fish-oil", "multivitamin"],
   suggestionPriority: 8,
   corePriority: 8,
 },
 {
   id: "vitamin-c",
   name: "vitamin-c",
   displayName: "Vitamin C",
   description:
     "Immune and antioxidant support for everyday wellness.",
   category: "immune_support",
   defaultTiming: "morning",
   monthlyPrice: 18,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["immune_support", "hair_skin_nails", "general_wellness", "recovery"],
   pairsWellWith: ["zinc", "quercetin", "collagen", "iron", "vitamin-e"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "vitamin-e",
   name: "vitamin-e",
   displayName: "Vitamin E",
   description:
     "Supports antioxidant activity, skin wellness, and cellular health.",
   category: "antioxidant_skin",
   defaultTiming: "morning",
   monthlyPrice: 18,
   dosage: "1 softgel",
   brand: "VidaPouch",
   supports: ["healthy_aging", "hair_skin_nails", "immune_support", "general_wellness"],
   pairsWellWith: ["vitamin-c", "omega3", "fish-oil", "collagen"],
   suggestionPriority: 6,
   corePriority: 5,
 },
 {
   id: "zinc",
   name: "zinc",
   displayName: "Zinc",
   description:
     "Supports immune health, recovery, and daily wellness.",
   category: "immune_recovery",
   defaultTiming: "morning",
   monthlyPrice: 16,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["immune_support", "recovery", "mens_health", "hair_skin_nails"],
   pairsWellWith: ["vitamin-c", "magnesium", "multivitamin"],
   suggestionPriority: 7,
   corePriority: 7,
 },
 {
   id: "b-complex",
   name: "b-complex",
   displayName: "B Complex",
   description:
     "Supports daily energy production, metabolism, and nervous system function. Includes key B vitamins such as B3.",
   category: "energy_metabolism",
   defaultTiming: "morning",
   monthlyPrice: 22,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["energy", "metabolism_weight", "focus_brain", "general_wellness"],
   pairsWellWith: ["coq10", "rhodiola", "omega3", "fish-oil", "acetyl-l-carnitine", "b12"],
   suggestionPriority: 8,
   corePriority: 8,
 },
 {
   id: "b12",
   name: "b12",
   displayName: "Vitamin B12",
   description:
     "Supports energy production, nervous system health, and cognitive wellness.",
   category: "energy_focus",
   defaultTiming: "morning",
   monthlyPrice: 19,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["energy", "focus_brain", "general_wellness"],
   pairsWellWith: ["b-complex", "coq10", "omega3", "fish-oil"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "coq10",
   name: "coq10",
   displayName: "CoQ10",
   description:
     "Supports cellular energy production and cardiovascular wellness.",
   category: "energy_heart",
   defaultTiming: "morning",
   monthlyPrice: 32,
   dosage: "1 softgel",
   brand: "VidaPouch",
   supports: ["energy", "heart_circulation", "healthy_aging", "endurance"],
   pairsWellWith: ["omega3", "fish-oil", "b-complex", "b12", "creatine", "rhodiola"],
   suggestionPriority: 8,
   corePriority: 8,
 },
 {
   id: "magnesium",
   name: "magnesium",
   displayName: "Magnesium Glycinate",
   description:
     "Supports recovery, nervous system balance, and evening relaxation.",
   category: "sleep_stress_recovery",
   defaultTiming: "evening",
   monthlyPrice: 24,
   dosage: "2 capsules",
   brand: "VidaPouch",
   supports: ["sleep", "stress_mood", "recovery", "bone_joint", "muscle_strength"],
   pairsWellWith: ["melatonin", "l-theanine", "ashwagandha", "vitamin-d3"],
   suggestionPriority: 9,
   corePriority: 10,
 },
 {
   id: "melatonin",
   name: "melatonin",
   displayName: "Melatonin",
   description:
     "Optional nighttime support for sleep onset and healthy sleep routines.",
   category: "sleep_support",
   defaultTiming: "evening",
   monthlyPrice: 19,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["sleep"],
   pairsWellWith: ["magnesium", "l-theanine"],
   suggestionPriority: 10,
   corePriority: 4,
   isOptionalOnly: true,
 },
 {
   id: "l-theanine",
   name: "l-theanine",
   displayName: "L-Theanine",
   description:
     "Promotes calm focus and stress support without drowsiness.",
   category: "stress_focus",
   defaultTiming: "evening",
   monthlyPrice: 21,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["stress_mood", "focus_brain", "sleep"],
   pairsWellWith: ["magnesium", "melatonin", "ashwagandha", "lion-mane"],
   suggestionPriority: 9,
   corePriority: 7,
 },
 {
   id: "ashwagandha",
   name: "ashwagandha",
   displayName: "Ashwagandha",
   description:
     "Adaptogenic support for stress resilience and recovery.",
   category: "stress_support",
   defaultTiming: "evening",
   monthlyPrice: 27,
   dosage: "2 capsules",
   brand: "VidaPouch",
   supports: ["stress_mood", "sleep", "recovery"],
   pairsWellWith: ["magnesium", "l-theanine", "rhodiola"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "rhodiola",
   name: "rhodiola",
   displayName: "Rhodiola Rosea",
   description:
     "Adaptogenic support for stamina, stress balance, and mental performance.",
   category: "stress_energy",
   defaultTiming: "morning",
   monthlyPrice: 26,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["energy", "stress_mood", "endurance", "focus_brain"],
   pairsWellWith: ["b-complex", "coq10", "ashwagandha"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "lion-mane",
   name: "lion-mane",
   displayName: "Lion’s Mane",
   description:
     "Supports focus, cognition, and long-term brain wellness.",
   category: "brain_focus",
   defaultTiming: "morning",
   monthlyPrice: 31,
   dosage: "2 capsules",
   brand: "VidaPouch",
   supports: ["focus_brain", "healthy_aging"],
   pairsWellWith: ["omega3", "fish-oil", "bacopa", "alpha-gpc", "l-theanine"],
   suggestionPriority: 9,
   corePriority: 8,
 },
 {
   id: "bacopa",
   name: "bacopa",
   displayName: "Bacopa Monnieri",
   description:
     "Supports memory, focus, and cognitive wellness.",
   category: "brain_focus",
   defaultTiming: "morning",
   monthlyPrice: 28,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["focus_brain", "healthy_aging"],
   pairsWellWith: ["lion-mane", "omega3", "fish-oil", "alpha-gpc"],
   suggestionPriority: 7,
   corePriority: 6,
 },
 {
   id: "alpha-gpc",
   name: "alpha-gpc",
   displayName: "Alpha GPC",
   description:
     "Supports focus, mental performance, and cognitive clarity.",
   category: "brain_focus",
   defaultTiming: "morning",
   monthlyPrice: 34,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["focus_brain", "energy"],
   pairsWellWith: ["lion-mane", "bacopa", "b-complex", "b12"],
   suggestionPriority: 7,
   corePriority: 6,
 },
 {
   id: "probiotic",
   name: "probiotic",
   displayName: "Probiotic",
   description:
     "Supports gut balance and digestive wellness.",
   category: "gut_health",
   defaultTiming: "morning",
   monthlyPrice: 26,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["gut_health", "immune_support", "general_wellness"],
   pairsWellWith: ["digestive-enzymes", "fiber", "vitamin-c", "multivitamin"],
   suggestionPriority: 9,
   corePriority: 8,
 },
 {
   id: "fiber",
   name: "fiber",
   displayName: "Daily Fiber Support",
   description:
     "Supports digestion, gut wellness, and healthy daily regularity.",
   category: "gut_health",
   defaultTiming: "morning",
   monthlyPrice: 20,
   dosage: "2 capsules",
   brand: "VidaPouch",
   supports: ["gut_health", "metabolism_weight", "general_wellness"],
   pairsWellWith: ["probiotic", "digestive-enzymes"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "digestive-enzymes",
   name: "digestive-enzymes",
   displayName: "Digestive Enzymes",
   description:
     "Supports digestion and nutrient breakdown with meals.",
   category: "gut_health",
   defaultTiming: "morning",
   monthlyPrice: 23,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["gut_health"],
   pairsWellWith: ["probiotic", "fiber", "multivitamin"],
   suggestionPriority: 7,
   corePriority: 6,
 },
 {
   id: "creatine",
   name: "creatine",
   displayName: "Creatine Capsules",
   description:
     "Supports strength, recovery, and physical performance.",
   category: "performance",
   defaultTiming: "morning",
   monthlyPrice: 29,
   dosage: "4 capsules",
   brand: "VidaPouch",
   supports: ["muscle_strength", "endurance", "recovery", "focus_brain"],
   pairsWellWith: ["electrolytes", "magnesium", "coq10", "zinc"],
   suggestionPriority: 9,
   corePriority: 9,
 },
 {
   id: "electrolytes",
   name: "electrolytes",
   displayName: "Electrolyte Support",
   description:
     "Supports hydration, endurance, and physical recovery.",
   category: "hydration_performance",
   defaultTiming: "morning",
   monthlyPrice: 23,
   dosage: "2 capsules",
   brand: "VidaPouch",
   supports: ["hydration", "endurance", "recovery", "muscle_strength"],
   pairsWellWith: ["creatine", "magnesium", "beet-root"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "turmeric",
   name: "turmeric",
   displayName: "Turmeric Curcumin",
   description:
     "Supports recovery, joint comfort, and inflammation balance.",
   category: "joint_recovery",
   defaultTiming: "morning",
   monthlyPrice: 25,
   dosage: "2 capsules",
   brand: "VidaPouch",
   supports: ["bone_joint", "recovery", "healthy_aging"],
   pairsWellWith: ["boswellia", "glucosamine", "omega3", "fish-oil"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "glucosamine",
   name: "glucosamine",
   displayName: "Glucosamine",
   description:
     "Supports joint comfort, mobility, and cartilage wellness.",
   category: "joint_support",
   defaultTiming: "morning",
   monthlyPrice: 26,
   dosage: "2 capsules",
   brand: "VidaPouch",
   supports: ["bone_joint", "recovery"],
   pairsWellWith: ["turmeric", "boswellia", "collagen"],
   suggestionPriority: 7,
   corePriority: 7,
 },
 {
   id: "boswellia",
   name: "boswellia",
   displayName: "Boswellia",
   description:
     "Supports joint comfort and recovery wellness.",
   category: "joint_recovery",
   defaultTiming: "morning",
   monthlyPrice: 24,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["bone_joint", "recovery"],
   pairsWellWith: ["turmeric", "glucosamine"],
   suggestionPriority: 7,
   corePriority: 6,
 },
 {
   id: "calcium",
   name: "calcium",
   displayName: "Calcium",
   description:
     "Supports bone strength and mineral balance.",
   category: "bone_health",
   defaultTiming: "morning",
   monthlyPrice: 18,
   dosage: "2 capsules",
   brand: "VidaPouch",
   supports: ["bone_joint"],
   pairsWellWith: ["vitamin-d3", "vitamin-k2", "magnesium"],
   suggestionPriority: 7,
   corePriority: 7,
 },
 {
   id: "vitamin-k2",
   name: "vitamin-k2",
   displayName: "Vitamin K2",
   description:
     "Supports bone and cardiovascular wellness alongside Vitamin D.",
   category: "bone_heart",
   defaultTiming: "morning",
   monthlyPrice: 21,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["bone_joint", "heart_circulation"],
   pairsWellWith: ["vitamin-d3", "calcium", "omega3", "fish-oil"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "biotin",
   name: "biotin",
   displayName: "Biotin",
   description: "Hair, skin, and nail wellness support.",
   category: "beauty",
   defaultTiming: "morning",
   monthlyPrice: 18,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["hair_skin_nails"],
   pairsWellWith: ["collagen", "hyaluronic-acid", "vitamin-c"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "collagen",
   name: "collagen",
   displayName: "Collagen Capsules",
   description:
     "Supports skin, connective tissue, and recovery wellness.",
   category: "beauty_recovery",
   defaultTiming: "morning",
   monthlyPrice: 34,
   dosage: "3 capsules",
   brand: "VidaPouch",
   supports: ["hair_skin_nails", "recovery", "bone_joint"],
   pairsWellWith: ["vitamin-c", "vitamin-e", "biotin", "hyaluronic-acid"],
   suggestionPriority: 8,
   corePriority: 8,
 },
 {
   id: "hyaluronic-acid",
   name: "hyaluronic-acid",
   displayName: "Hyaluronic Acid",
   description:
     "Supports skin hydration and connective tissue wellness.",
   category: "beauty_skin",
   defaultTiming: "morning",
   monthlyPrice: 24,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["hair_skin_nails", "bone_joint"],
   pairsWellWith: ["collagen", "biotin", "vitamin-c", "vitamin-e"],
   suggestionPriority: 7,
   corePriority: 6,
 },
 {
   id: "berberine",
   name: "berberine",
   displayName: "Berberine",
   description:
     "Supports metabolic wellness and healthy blood sugar balance.",
   category: "metabolic_health",
   defaultTiming: "morning",
   monthlyPrice: 33,
   dosage: "2 capsules",
   brand: "VidaPouch",
   supports: ["metabolism_weight"],
   pairsWellWith: ["green-tea-extract", "acetyl-l-carnitine", "probiotic", "fiber"],
   suggestionPriority: 8,
   corePriority: 8,
 },
 {
   id: "green-tea-extract",
   name: "green-tea-extract",
   displayName: "Green Tea Extract",
   description:
     "Supports metabolism, antioxidant status, and daily energy.",
   category: "metabolism_energy",
   defaultTiming: "morning",
   monthlyPrice: 22,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["metabolism_weight", "energy", "healthy_aging"],
   pairsWellWith: ["berberine", "acetyl-l-carnitine", "b-complex"],
   suggestionPriority: 7,
   corePriority: 6,
 },
 {
   id: "nac",
   name: "nac",
   displayName: "NAC",
   description:
     "Supports antioxidant activity, recovery, and cellular wellness.",
   category: "antioxidant_recovery",
   defaultTiming: "morning",
   monthlyPrice: 25,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["healthy_aging", "immune_support", "liver_support", "recovery"],
   pairsWellWith: ["milk-thistle", "quercetin", "vitamin-c", "vitamin-e"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "milk-thistle",
   name: "milk-thistle",
   displayName: "Milk Thistle",
   description:
     "Supports liver wellness and antioxidant balance.",
   category: "liver_support",
   defaultTiming: "morning",
   monthlyPrice: 21,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["liver_support", "healthy_aging"],
   pairsWellWith: ["nac", "turmeric"],
   suggestionPriority: 7,
   corePriority: 6,
 },
 {
   id: "quercetin",
   name: "quercetin",
   displayName: "Quercetin",
   description:
     "Supports immune balance and antioxidant wellness.",
   category: "immune_antioxidant",
   defaultTiming: "morning",
   monthlyPrice: 24,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["immune_support", "healthy_aging"],
   pairsWellWith: ["vitamin-c", "vitamin-e", "zinc", "nac"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "resveratrol",
   name: "resveratrol",
   displayName: "Resveratrol",
   description:
     "Supports healthy aging, antioxidant activity, and cellular wellness.",
   category: "longevity",
   defaultTiming: "morning",
   monthlyPrice: 30,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["healthy_aging", "heart_circulation"],
   pairsWellWith: ["omega3", "fish-oil", "nac", "coq10"],
   suggestionPriority: 7,
   corePriority: 6,
 },
 {
   id: "saffron",
   name: "saffron",
   displayName: "Saffron",
   description:
     "Supports mood balance, emotional wellness, and calm.",
   category: "mood_support",
   defaultTiming: "morning",
   monthlyPrice: 29,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["stress_mood"],
   pairsWellWith: ["l-theanine", "magnesium", "ashwagandha"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "5-htp",
   name: "5-htp",
   displayName: "5-HTP",
   description:
     "Supports mood balance and nighttime relaxation.",
   category: "mood_sleep",
   defaultTiming: "evening",
   monthlyPrice: 24,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["stress_mood", "sleep"],
   pairsWellWith: ["magnesium", "l-theanine"],
   suggestionPriority: 7,
   corePriority: 5,
   isOptionalOnly: true,
 },
 {
   id: "ginkgo",
   name: "ginkgo",
   displayName: "Ginkgo Biloba",
   description:
     "Supports circulation, cognitive wellness, and mental clarity.",
   category: "circulation_brain",
   defaultTiming: "morning",
   monthlyPrice: 22,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["focus_brain", "heart_circulation"],
   pairsWellWith: ["omega3", "fish-oil", "lion-mane", "coq10"],
   suggestionPriority: 7,
   corePriority: 6,
 },
 {
   id: "beet-root",
   name: "beet-root",
   displayName: "Beet Root",
   description:
     "Supports circulation, endurance, and workout performance.",
   category: "circulation_performance",
   defaultTiming: "morning",
   monthlyPrice: 23,
   dosage: "2 capsules",
   brand: "VidaPouch",
   supports: ["heart_circulation", "endurance", "muscle_strength"],
   pairsWellWith: ["electrolytes", "coq10", "creatine"],
   suggestionPriority: 7,
   corePriority: 6,
 },
 {
   id: "iron",
   name: "iron",
   displayName: "Iron",
   description:
     "Supports healthy iron levels, energy, and red blood cell wellness.",
   category: "energy_womens_health",
   defaultTiming: "morning",
   monthlyPrice: 18,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["energy", "womens_health"],
   pairsWellWith: ["vitamin-c", "multivitamin"],
   suggestionPriority: 6,
   corePriority: 5,
   isOptionalOnly: true,
 },
 {
   id: "maca",
   name: "maca",
   displayName: "Maca Root",
   description:
     "Supports energy, vitality, and hormonal wellness.",
   category: "hormone_energy",
   defaultTiming: "morning",
   monthlyPrice: 23,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["hormone_support", "energy", "womens_health", "mens_health"],
   pairsWellWith: ["inositol", "dim", "b-complex"],
   suggestionPriority: 7,
   corePriority: 6,
 },
 {
   id: "inositol",
   name: "inositol",
   displayName: "Inositol",
   description:
     "Supports hormonal wellness, mood balance, and metabolic health.",
   category: "hormone_mood",
   defaultTiming: "evening",
   monthlyPrice: 27,
   dosage: "2 capsules",
   brand: "VidaPouch",
   supports: ["hormone_support", "stress_mood", "metabolism_weight", "womens_health"],
   pairsWellWith: ["magnesium", "dim", "maca"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "dim",
   name: "dim",
   displayName: "DIM",
   description:
     "Supports estrogen metabolism and hormonal balance.",
   category: "hormone_support",
   defaultTiming: "morning",
   monthlyPrice: 28,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["hormone_support", "womens_health"],
   pairsWellWith: ["inositol", "maca", "magnesium"],
   suggestionPriority: 7,
   corePriority: 6,
 },
 {
   id: "cranberry",
   name: "cranberry",
   displayName: "Cranberry",
   description:
     "Supports urinary tract wellness and antioxidant balance.",
   category: "womens_health",
   defaultTiming: "morning",
   monthlyPrice: 19,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["womens_health", "immune_support"],
   pairsWellWith: ["probiotic", "vitamin-c"],
   suggestionPriority: 6,
   corePriority: 5,
 },
 {
   id: "prenatal-multi",
   name: "prenatal-multi",
   displayName: "Prenatal Multi",
   description:
     "Foundational prenatal vitamin and mineral support.",
   category: "prenatal",
   defaultTiming: "morning",
   monthlyPrice: 35,
   dosage: "2 capsules",
   brand: "VidaPouch",
   supports: ["womens_health"],
   pairsWellWith: ["omega3", "fish-oil", "iron", "vitamin-d3"],
   suggestionPriority: 4,
   corePriority: 4,
   isOptionalOnly: true,
 },
 {
   id: "saw-palmetto",
   name: "saw-palmetto",
   displayName: "Saw Palmetto",
   description:
     "Supports men’s wellness and prostate health.",
   category: "mens_health",
   defaultTiming: "morning",
   monthlyPrice: 23,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["mens_health"],
   pairsWellWith: ["zinc", "lycopene", "omega3", "fish-oil"],
   suggestionPriority: 7,
   corePriority: 6,
 },
 {
   id: "lycopene",
   name: "lycopene",
   displayName: "Lycopene",
   description:
     "Supports antioxidant activity and men’s wellness.",
   category: "mens_health_antioxidant",
   defaultTiming: "morning",
   monthlyPrice: 22,
   dosage: "1 softgel",
   brand: "VidaPouch",
   supports: ["mens_health", "healthy_aging", "heart_circulation"],
   pairsWellWith: ["saw-palmetto", "zinc", "omega3", "fish-oil"],
   suggestionPriority: 6,
   corePriority: 5,
 },
 {
   id: "lutein",
   name: "lutein",
   displayName: "Lutein",
   description:
     "Supports eye health and visual wellness.",
   category: "eye_health",
   defaultTiming: "morning",
   monthlyPrice: 21,
   dosage: "1 softgel",
   brand: "VidaPouch",
   supports: ["eye_health", "healthy_aging"],
   pairsWellWith: ["omega3", "fish-oil", "vitamin-c", "zinc"],
   suggestionPriority: 8,
   corePriority: 7,
 },
 {
   id: "acetyl-l-carnitine",
   name: "acetyl-l-carnitine",
   displayName: "Acetyl L-Carnitine",
   description:
     "Supports cellular energy, metabolism, and cognitive wellness.",
   category: "energy_brain_metabolism",
   defaultTiming: "morning",
   monthlyPrice: 27,
   dosage: "1 capsule",
   brand: "VidaPouch",
   supports: ["energy", "focus_brain", "metabolism_weight", "healthy_aging"],
   pairsWellWith: ["coq10", "b-complex", "b12", "green-tea-extract"],
   suggestionPriority: 7,
   corePriority: 6,
 },
];