export const SUPPLEMENT_CATALOG = [
    "5-HTP",
    "Acetyl L-Carnitine",
    "Alpha GPC",
    "Ashwagandha",
    "Astaxanthin",
    "B Complex",
    "Bacopa Monnieri",
    "Beet Root",
    "Berberine",
    "Biotin",
    "Boron",
    "Calcium",
    "Choline",
    "Chromium",
    "CoQ10",
    "Collagen",
    "Creatine",
    "Curcumin",
    "Digestive Enzymes",
    "Electrolytes",
    "Fiber",
    "Fish Oil",
    "Folate",
    "Garlic",
    "Ginkgo Biloba",
    "Glucosamine",
    "Green Tea Extract",
    "Hyaluronic Acid",
    "Inositol",
    "Iron",
    "L-Carnitine",
    "L-Theanine",
    "Lion's Mane",
    "Lutein",
    "Lycopene",
    "Maca",
    "Magnesium Citrate",
    "Magnesium Glycinate",
    "Magnesium Malate",
    "Magnesium Oxide",
    "Magnesium Threonate",
    "Melatonin",
    "Milk Thistle",
    "Multivitamin",
    "NAC",
    "NMN",
    "Omega-3",
    "Potassium",
    "Probiotic",
    "Protein",
    "Psyllium Husk",
    "Quercetin",
    "Resveratrol",
    "Rhodiola Rosea",
    "Saw Palmetto",
    "Selenium",
    "Turmeric",
    "Vitamin A",
    "Vitamin B1",
    "Vitamin B12",
    "Vitamin B2",
    "Vitamin B6",
    "Vitamin C",
    "Vitamin D3",
    "Vitamin E",
    "Vitamin K2",
    "Zinc",
   ];